version: "3.8"
services:
  gamera-api:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/usr/src/gamera-api
    ports:
      - "3004:3004"
  gamera-mongo:
    networks:
      - gamera
      - default