version: "3.8"
services:
  gamera-api:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/usr/src/gamera-api
    ports:
      - "3004:3004"
  gamera-mongo:
    networks:
      - gamera
      - default
  gamera-parse-dashboard:
    image: parseplatform/parse-dashboard
    ports:
      - "4044:4044"
    environment:
      - PORT=4044
    env_file:
      - ./env/gamera-parse-dashboard.env
    command: parse-dashboard